kujaff\CryptoCurrenciesPoolsBundle\Entity\Pool:
    type: entity
    table: pools
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '50'
        address:
            type: string
            length: 255
        hashrate:
            type: integer
            nullable: true
        efficiency:
            type: decimal
            precision: 2
            scale: 2
            nullable: true
        taxeFee:
            type: decimal
            precision: 2
            scale: 2
            nullable: true
        lastUpdate:
            type: datetime
            nullable: true
        refreshErrors:
            type: json_array
            nullable: true
        refreshEnabled:
            type: boolean
            default: true
            
    oneToMany:
        servers:
            targetEntity: kujaff\CryptoCurrenciesPoolsBundle\Entity\Server
            mappedBy: pool
            fetch: EAGER
            cascade:
                - persist
            
    manyToOne:
        currency:
            targetEntity: kujaff\CryptoCurrenciesBundle\Entity\Currency
            joinColumn:
                nullable: false
            fetch: EAGER
            
    oneToOne:
        api:
            targetEntity: kujaff\CryptoCurrenciesPoolsBundle\Entity\Api
            fetch: EAGER
            cascade:
                - persist
                
        blocks:
            targetEntity: kujaff\CryptoCurrenciesPoolsBundle\Entity\Blocks
            fetch: EAGER
            cascade:
                - persist
                
        network:
            targetEntity: kujaff\CryptoCurrenciesPoolsBundle\Entity\Network
            fetch: EAGER
            cascade:
                - persist
                
        shares:
            targetEntity: kujaff\CryptoCurrenciesPoolsBundle\Entity\Shares
            fetch: EAGER
            cascade:
                - persist
                
        user:
            targetEntity: kujaff\CryptoCurrenciesPoolsBundle\Entity\User
            fetch: EAGER
            cascade:
                - persist
                
        
            
    lifecycleCallbacks: {  }