kujaff\CryptoCurrenciesPoolsBundle\Entity\Pool:
    type: entity
    table: pools
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '50'
        address:
            type: string
            length: 255
        hashrate:
            type: integer
            nullable: true
        efficiency:
            type: decimal
            precision: 2
            scale: 2
            nullable: true
        estimatedTime:
            type: integer
            nullable: true
        taxeFee:
            type: decimal
            precision: 2
            scale: 2
            nullable: true
            
    oneToMany:
        servers:
            targetEntity: kujaff\CryptoCurrenciesPoolsBundle\Entity\Server
            mappedBy: pool
            fetch: EAGER
            
    oneToOne:
        api:
            targetEntity: kujaff\CryptoCurrenciesPoolsBundle\Entity\Api
            fetch: EAGER
        blocks:
            targetEntity: kujaff\CryptoCurrenciesPoolsBundle\Entity\Blocks
            fetch: EAGER
        network:
            targetEntity: kujaff\CryptoCurrenciesPoolsBundle\Entity\Network
            fetch: EAGER
        shares:
            targetEntity: kujaff\CryptoCurrenciesPoolsBundle\Entity\Shares
            fetch: EAGER
        user:
            targetEntity: kujaff\CryptoCurrenciesPoolsBundle\Entity\User
            fetch: EAGER
            
    lifecycleCallbacks: {  }