services:
    
    cryptocurrenciespools.installer:
        class: kujaff\CryptoCurrenciesPoolsBundle\Install\Installer
        arguments: [ @service_container ]
        tags:
            - { name: bundle.install }
            - { name: bundle.update }
            - { name: bundle.uninstall }

    cryptocurrenciespools:
        class: kujaff\CryptoCurrenciesPoolsBundle\Pools\Service
        arguments: [ @service_container ]
    
    onsavepool:
        class: kujaff\CryptoCurrenciesPoolsBundle\Pools\DoctrineListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }